yarnPath: .yarn/releases/yarn-4.12.0.cjs
nodeLinker: node-modules

npmScopes:
    ingress-shards:
        npmRegistryServer: "https://npm.pkg.github.com"

npmRegistries:
    "https://npm.pkg.github.com":
        npmAuthToken: "${GITHUB_TOKEN:-}"
